### ISSUE TITLE
Update tips

### ISSUE THREAD

**Issue by Slayer95** [inferno8/wesnoth-To_Lands_Unknown#21]
A few scenarios have too many tips, while others lack important ones. This is particularly notable for the Hard difficulty, in which they could/should be removed.

1. S01 Highest Tiers - It's not clear that the player absolutely MUST hurry in order not to loss on turn limit.
2. S03 Near the Jungle
- No mention of the healing properties of oasis.
- [Normal mode] Rhaxiz could use an "invulnerable" icon. (https://github.com/wesnoth/wesnoth/pull/7363)
3. S08 Ka-gatta - There's an oasis here, too.
4. S15 Abyssal Rebellion
- Way too many tips (mostly voiced by banisher Semir)
- In particular, that Semir will leave is mostly an irrelevant fact and an spoiler.
5. S16 Deffense of Saffaros
- Spoiler on Atiros' fate can be left out.
6. S19 Sky Kingdom
- ~~Except for possibly some niche gameplay, gold is meaningless afterwards. This should be conveyed or fixed somehow.~~ (Fixed in #28)

**Comment by inferno8** [comment]
> 1. S01 Highest Tiers - It's not clear that the player absolutely MUST hurry in order not to loss on turn limit.

This scenario needs a small tweak. There should be 2 winning conditions: entering the palace or defeating all enemies (within the turn limit). The latter should result in Mehir automatically running to the palace gates once there are no hostile units on the map.

> 6\. S15 Abyssal Rebellion
> * Way too many tips (mostly voiced by banisher Semir)

Banisher's tips are part of training and are also used to immerse players in the world of TLU. I am not going to change that.

> * In particular, that Semir will leave is mostly an irrelevant fact and an spoiler.
> * Spoiler on Atiros' fate can be left out.

The purpose of informing players about these two characters leaving in the next scenario is to avoid situations where xp is wasted on them. Thanks to these notes, players can feed xp to other units without any unpleasant surprises.

**Comment by Slayer95** [comment]
> where xp is wasted on them. Thanks to these notes, players can feed xp to other units without any unpleasant surprises.

However, they are already max level units. That alone should be enough reason for players not to feed them exp. In the case of Semir, he ought to banish as much as possible the whole scenario, and even if you decide to level up Dispellers, that's not a good idea either since Abyssal Rebellion is the last scenario to feature banishable enemies.

> Banisher's tips are part of training

They are all reiteration of content from previous scenarios. It feels like Abyssal Rebellion is the real schooling scenario as opposed to Tar Tabar's comic relief.

> immerse players

Counterproductive. Both the tone of Semir, as well as Mehir's clueless act make no sense. Mehir is already a city leader by that time! Even if it were the case that the player has skipped most dialogues, Mehir <i>himself</i> shouldn't have.

**Comment by inferno8** [comment]
> However, they are already max level units. That alone should be enough reason for players not to feed them exp.

Maybe so, but iirc the decision to include the warning was based on feedback from players. Older TLU versions didn't have that. I don't remember details, but maybe it was also about helping players realize that some units won't accompany them for the rest of the campaign. Knowing that, they (players) could adjust their tactics accordingly (for example by sending Semir to one of the map corners to distract enemies, because, well, he is expendable).

> They are all reiteration of content from previous scenarios.

Repeating old stuff could also be part of training procedures, but I think you might be on to something here.

> Counterproductive. Both the tone of Semir, as well as Mehir's clueless act make no sense. Mehir is already a city leader by that time! Even if it were the case that the player has skipped most dialogues, Mehir himself shouldn't have.

Mehir became a city leader in very extraordinary circumstances. Normally this title would have never been unattainable to him. Because of that reason the Instructor assumes Mehir's knowledge is still limited and routinely explains everything (btw, this is actually good for players with short memory).
I do realize that some other players may find this repetition irritating, so adding an option to skip some parts might be a way to go. And actually... this has already been implemented for badass mode where you can just leave the place in the middle of the training by moving Mehir to the eastern border of the map.
But for regular gameplay maybe it would be good to give players a choice, so that they can skip the part about Dimensional Gates if they wish to. Mehir could say that he already knows how these things work, so there is no need for explanation (especially in case he already leveled up at least one gate in the past). A variable check could also be implemented for that purpose to spice the dialog up. Players with short memory on the other hand could ask for a quick guide. That way I wouldn't have to remove many lines of dialog. That could work.

**Comment by Slayer95** [comment]
> maybe it was also about helping players realize that some units won't accompany them for the rest of the campaign. Knowing that, they (players) could adjust their tactics accordingly (for example by sending Semir to one of the map corners to distract enemies, because, well, he is expendable).

I guess sacrificing a named character was actually an option. Fair enough.

> This is actually good for players with short memory

I'm mostly fine with this, but repeating content from S14 _too_ crosses the line imo.

> And actually... this has already been implemented for badass mode where you can just leave the place in the middle of the training by moving Mehir to the eastern border of the map.

This is a good point. In the case Mehir actually left class, then it would be logical for him to catch up in Abyssal Rebellion, and

> especially in case he already leveled up at least one gate in the past

This check would cover it, as well as going further in a good direction imo.

That should be enough.
