### ISSUE TITLE
Villages in S10 Chaos

### ISSUE THREAD

**Issue by Slayer95** [inferno8/wesnoth-To_Lands_Unknown#61]
- It's not obvious that the tents next to the starting castle are actually villages.
- After the red abyss portal is opened, Aerius' villages are razed, but the former aren't. Yet, any units standing on the villages or further from the portal will get sucked.

**Comment by inferno8** [comment]
> * It's not obvious that the tents next to the starting castle are actually villages.

Adding a note about the purpose of the tents should do the trick.

> * After the red abyss portal is opened, Aerius' villages are razed, but the former aren't. Yet, any units standing on the villages or further from the portal will get sucked.

Good observation. In this case maybe the starting area should be excluded from the effects of the portal. But then this could make the scenario easier, because the player could just sit in the camp and recruit without any fear of the portal in front of them. 
The best option would be to destroy the player's camp and animate the whole sequence, but this may not be easy, due to the camp being situated further away from the portal and not being visible during the activation sequence (at least with the default zoom level and full hd screen resolution). I'll have to think about making a convincing animation for this...

**Comment by Slayer95** [comment]
> Adding a note about the purpose of the tents should do the trick.

As you may have realized, I am not a fan of adding too many notes. Adding a red ownership flag to one of them should be enough IMO.

**Comment by inferno8** [comment]
Ok, this could also work.
